### PR TITLE
"Pass If Equal Timestamp" test implementation added

### PR DESCRIPTION
**Pull request by kosist**
Added implementation of "Pass If Equal Timestamp" test, as it was mentioned in [Future work](https://github.com/WiresmithTech/VITAC#future-work) section of readme file.
Also, added test cases for verification of module functionality.
VI converts input timestamps to date time records, and compares elements one-by-one. In case of failure, it will list of failed components and their values. Day of week, day of year and DST components of date time records are not included into comparison report.
@JamesMc86, could you, please, review the code, whether it could be implemented like this?
Thanks a lot!

### CODE REVIEW

**Comment by JamesWiresmith** [comment]
Hi Kosist,

Thanks for the contribution. I have a concern with this implementation though and the conversion to components. This starts to introduce timezone concerns and actually I think I am already seeing this where tests are failing because the hours in the descriptions are wrong.

I would actually suggest converting to a double internally and comparing there with a custom message that prints the whole timestamps out. There is scope to reuse the internal comparison from the numeric test.

**Comment by kosist** [comment]
Hello @JamesMc86,

thank you for the feedback!

I was thinking about timezones, but seems that it should not be an issue during unit testing. Absolute timestamp values will be the same, regardless timezone, because of nature of unit test. We are not comparing during unit test data, received from different machines in different timezones. If we have some algorithm, which compares time (of waveform, files creation, etc.), we anyway would test it either based on absolute timestamp values, or "relative" - thus, this algorithm could be tested with the same result in different timezones. 
Like, if log file should be created at 12 AM, then this time will be the same across timezones: creation will happen by local timezone, and comparison is done by statically defined timestamp, which at the end correspond to local 12 AM.
Maybe I'm wrong, so please, just give some example, because now I do not understand, when timezone could cause issue during comparison - maybe I'm missing something trivial then...

Result of comparison of timestamp components, or double will be the same, if I'm not mistaken; and conversion of components was implemented, to highlight exactly those components which fail. But then, just prining of whole timestamp is easier, so then I could change it to this, as you've suggested.
So then, please, I'll discard this pull request, modify the code, and create new one.

Thank you very much!

Sincerely, kosist.

**Comment by JamesWiresmith** [comment]
> Maybe I'm wrong, so please, just give some example, because now I do not understand, when timezone could cause issue during comparison - maybe I'm missing something trivial then...

When you have a timestamp constant on your diagram LabVIEW shows you your local format but stores in seconds (UTC). When you do the conversion to the cluster format it gets converted to local time OR UTC but loses knowledge of which it is. The failure is that you wrote the test results in CET (I'm guessing) but the conversion on my machine uses GMT so the time is out.

You are actually correct in saying this is probably not going to be a concern in most cases - your tests fail only because we are looking at the numbers in the results.

> Result of comparison of timestamp components, or double will be the same, if I'm not mistaken; and conversion of components was implemented, to highlight exactly those components which fail. But then, just prining of whole timestamp is easier, so then I could change it to this, as you've suggested.
So then, please, I'll discard this pull request, modify the code, and create new one.

Good question - personally I think a timestamp is simple enough that showing the whole timestamp is easy to read and might make it easier to track the failure so I prefer this approach to be honest.

Sorry for the changes required, I do appreciate your work. I should try and create issues for these where we can be a bit more detailed in what is hoped for.

**Comment by JamesWiresmith** [comment]
Oh the other benefit of the numeric comparison is to use a delta. I get it a lot where there maybe microseconds different and I just don't care. I use "set time to now" to generate test constants and always have to remember there are hidden microseconds which I need to null out.

**Comment by kosist** [comment]
No problem, thank you very much for the feedback!
I'll correct implementation, and create then new pull request.
Btw, delta is a great idea - those three "hidden" digits in timestamp sometimes could make one crazy )))
Thank you,
sincerely, kosist.

**Pull request closed without merging**
