### PR TITLE
Custom report message input

### PR DESCRIPTION
**Pull request by kosist**
Hello James,

let me ask you for a pull request of implemented issue #17 .

All methods, except "Pass If Matches Regular Expression.vi" have "custom report message" input on same position on connector pane. But, "Pass If Matches Regular Expression.vi" has already there boolean input "Show \ codes". Thus, in order to keep compatibility with previous versions of toolkit, "custom report message" input is shifted for this method, on connector pane.

Thank you very much,

Sincerely, Ivan.

### CODE REVIEW

**Comment by JamesWiresmith** [comment]
Sorry Kosist,

Just one minor thing - can you correct the subdiagram labels on the new tests? Just adjust sizing so that the text is all visible. It is mostly hidden at the minute.

Then I'm happy to merge this.

Cheers,
James

**Comment by kosist** [comment]
Hello James,

which labels do you mean please? I see them completely:
Tests, Labels
Could you, please, show how it is seen on your machine? Maybe, we use different application font...
Thanks a lot,

Sincerely, Ivan.

**Comment by JamesWiresmith** [comment]
Huh yeah - that is strange:
image

Do you have a non-default app font? Mines a fresh install on Windows 10 with no scaling

**Comment by kosist** [comment]
Hello. Could you please share details of failed check on CI server? Are there some issues with commit itself? Thanks a lot.

**Comment by JamesWiresmith** [comment]
Hi @kosist ,

Apologies - hadn't realised jenkins would feedback to here! It's a build server issue, not a code issue.

I also hadn't realised this hadn't been merged. I'll merge it now.

**Pull request merged**
